version: 2.1
orbs:
  maven: circleci/maven@2.1.1
jobs:
  jobpremaven:
    docker:
      - image: cimg/base:current
    type: build # or release, approval, no-op
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results

  jobincludemaven:
    machine: true
    type: build
    steps:
      - checkout

      - run:
          name: Build an image
          command: |
            docker build --tag japp .
      - run:
          name: Run application in background
          command: |
            docker run  -it --rm japp 

          background: true

      - run:
          name:  docker inspect
          command: |
            docker network inspect bridge

      - run:
          name: Create CHcommand2
          command: chmod 755 zap/wrk/zap.yaml

      - run:
          name: "lag hei"
          command: mkdir /home/circleci/project/target/hei

      - run:
          name: ZAP baseline scan of application
          command: |
            (         
            docker pull ghcr.io/zaproxy/zaproxy:bare && \
            docker pull zaproxy/zap-bare && \
            docker run -u root -v $(pwd):/zap/wrk:rw --network="host"  zaproxy/zap-stable zap-baseline.py -t http://172.17.0.2:8080 -r scan-report.html
            
            )


  jobdeploy:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/guides/execution-managed/executor-intro/ & https://circleci.com/docs/reference/configuration-reference/#executor-job
    docker:
      # Specify the version you desire here
      # See: https://circleci.com/developer/images/image/cimg/base
      - image: google/cloud-sdk
    working_directory: ~/dev2

    # Add steps to the job
    # See: https://circleci.com/docs/guides/orchestrate/jobs-steps/#steps-overview & https://circleci.com/docs/reference/configuration-reference/#steps
    steps:
      # Checkout the code as the first step.
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
      - run:
          name: Create app.yaml
          command: chmod +x app.yaml.sh && ./app.yaml.sh > ./app.yaml
      - run:
          name: Set up GCloud
          command: |
            echo ${GOOGLE_PROJECT_ID} | 
            echo $GCLOUD_SERVICE_KEY | base64 --decode | gcloud auth activate-service-account --key-file=-
              gcloud --quiet config set project ${GOOGLE_PROJECT_ID}

workflows:
  workflowpremaven: 
    jobs:
      - jobpremaven:
          name: jobpremaven
          post-steps:
            - run:
                name: "Say hello"
                command: "echo Hello, World pre!"
          filters:
            branches:
              only: circleci-project-setup
  maven_test:
    jobs:
      - maven/test:
          command: '-X verify'
  workflowpostmaven:
    jobs:
      - jobincludemaven:
          name: jobincludemaven
          post-steps:
            - run:
                name: "lag hei"
                command: mkdir /home/circleci/project/target/hei
          filters:
            branches:
              only: circleci-project-setup
      - jobdeploy:
          name: deploy-staging
          post-steps:
            - run:
                name: Deploy app
                command: gcloud app deploy app.yaml
          filters:
            branches:
              only: circleci-project-setup
