version: 2.1
orbs:
  maven: circleci/maven@2.1.1
jobs:
  jobpremaven:
    docker:
      - image: cimg/base:2026.07
    
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results

  jobpostmaven:
    docker:
      - image: cimg/base:2026.07
    
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: "lag hei"
          command: mkdir /home/circleci/project/hei

  jobdeploy:
    docker:
      - image: google/cloud-sdk
    working_directory: ~/dev2

    steps:
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
      - run:
          name: Create app.yaml
          command: chmod +x app.yaml.sh && ./app.yaml.sh > ./app.yaml
      - run:
          name: Set up GCloud
          command: |
            echo ${GOOGLE_PROJECT_ID} | 
            echo $GCLOUD_SERVICE_KEY | base64 --decode | gcloud auth activate-service-account --key-file=-
              gcloud --quiet config set project ${GOOGLE_PROJECT_ID}

workflows:
  workflowpremaven: 
    jobs:
      - jobpremaven:
          name: jobpremaven
          post-steps:
            - run:
                name: "Say hello"
                command: "echo Hello, World pre!"
          filters:
            branches:
              only: circleci-project-setup
  maven_test:
    jobs:
      - maven/test:
          command: '-X verify'
          post-steps:
            - run:
                name: "Say hello after maven"
                command: mkdir /home/circleci/project/target/hei
            - run:
                name: Build an image
                command: |
                  docker build --tag $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME$CIRCLE_SHA1 .

            - run:
                name: Run application in background
                command: |
                  docker run  -t $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME$CIRCLE_SHA1
              background: true

  workflowpostmaven:
    jobs:
      - jobpostmaven:
          name: jobpostmaven
          post-steps:
            - run:
                name: "lag hei"
                command: mkdir /home/circleci/project/target/hei
          filters:
            branches:
              only: circleci-project-setup
